// using fake data JavaScript Array Object
const topLeaders = [
   {
      id: 101,
      name: "Jeff Bezos",
      age: 57,
      residence: "Seattle",
      role: "American entrepreneur",
      netWorth: "$177 billion",
      salary: 8990000000,
      img: "https://i.ibb.co/yqJzX13/Getty-Images-1036094130-cf8da629f9b44c81a0b1398311ac5787.webp",
      otherAssets: {
         asset1: "Blue Origin ",
         asset2: "The Washington Post",
      },
   },
   {
      id: 102,
      name: "Elon Musk",
      age: 50,
      residence: "Austin, Texas",
      role: "CEO of Tesla Motors",
      netWorth: "$151 billion",
      salary: 200000000,
      img: "https://i.ibb.co/kxNNN1t/elon-mask.webp",
      otherAssets: {
         asset1: "Space Exploration Technologies",
         asset2: "The Boring Company",
      },
   },
   {
      id: 103,
      name: "Bernard Arnault",
      age: 72,
      residence: "Paris",
      role: "Chief Executive of LVMH",
      netWorth: "$150 billion",
      salary: 3470000,
      img: "https://i.ibb.co/WfpR31N/Bernard-Arnault.webp",
      otherAssets: {
         asset1: "Moelis & Company equity",
         asset2: "Hermès equity",
      },
   },
   {
      id: 104,
      name: "Bill Gates",
      age: 65,
      residence: "Medina, Washington",
      role: "American Business Magnate",
      netWorth: "$124 billion",
      salary: 330000000,
      img: "https://i.ibb.co/PcN15Gj/gates.webp",
      otherAssets: {
         asset1: " Republic Services equity",
         asset2: "Canadian National Railway equity",
      },
   },
   {
      id: 105,
      name: "Mark Zuckerberg",
      age: 37,
      residence: "Palo Alto, Calif",
      role: "Chief Executive Officer of Facebook",
      netWorth: "$97 billion",
      salary: 25300000,
      img: "https://i.ibb.co/x7pH00B/mark.webp",
      otherAssets: {
         asset1: "Real Estate",
         asset2: "",
      },
   },
   {
      id: 106,
      name: "Warren Buffett",
      age: 91,
      residence: "Omaha, Nebraska",
      role: "Chief Executive Officer of  Berkshire Hathaway",
      netWorth: "$96 billion",
      salary: 328875000,
      img: "https://i.ibb.co/vPQsMCR/buffett.webp",
      otherAssets: {
         asset1: "Wells Fargo & Co. equity",
         asset2: "U.S. Bancorp equity",
      },
   },
   {
      id: 107,
      name: "Larry Ellison",
      age: 77,
      residence: "Lanai, Hawaii",
      role: "American Businessman & CEO of Oracle",
      netWorth: "$93 billion",
      salary: 283333378,
      img: "https://i.ibb.co/vhC8PTS/larry.webp",
      otherAssets: {
         asset1: "enterprise software giant Oracle",
         asset2: "Tesla equity",
      },
   },
   {
      id: 108,
      name: "Larry Page",
      age: 48,
      residence: "Palo Alto, California",
      role: " Computer Scientist",
      netWorth: "$91.5 billion",
      salary: 83333333,
      img: "https://i.ibb.co/6vSf1yj/page.webp",
      otherAssets: {
         asset1: "Alphabet",
         asset2: "",
      },
   },
   {
      id: 109,
      name: "Sergey Brin",
      age: 48,
      residence: "Los Altos, California",
      role: "American business magnate",
      netWorth: "$89 billion",
      salary: 11083334,
      img: "https://i.ibb.co/gtXvr96/brin.webp",
      otherAssets: {
         asset1: "Alphabet Ownership",
         asset2: "",
      },
   },
   {
      id: 110,
      name: "Mukesh Ambani",
      age: 64,
      residence: "Mumbai, India",
      role: "Indian Businessman",
      netWorth: "$84.5 billion",
      salary: 12500072,
      img: "https://i.ibb.co/b3bk0dB/mukesh.webp",
      otherAssets: {
         asset1: "Mumbai residential property",
         asset2: "",
      },
   },
];

const stringFied = JSON.stringify(topProgrammers);
console.log(stringFied);
